/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/templates/**/*.html", "./app/static/**/*.js"],
  darkMode: "class",
  plugins: [require("@tailwindcss/forms")],
  theme: {
    extend: {
      colors: {
        primary:                      "#84120c",
        "on-primary":                 "#ffffff",
        "primary-container":          "#a62c21",
        "on-primary-container":       "#ffc2b9",
        secondary:                    "#934b00",
        "on-secondary":               "#ffffff",
        "secondary-container":        "#fd9844",
        "secondary-fixed":            "#ffdcc5",
        "on-secondary-fixed":         "#301400",
        "on-secondary-fixed-variant": "#703800",
        tertiary:                     "#573b32",
        "on-tertiary":                "#ffffff",
        "tertiary-container":         "#715248",
        "on-tertiary-container":      "#f1c7bb",
        surface:                      "#fcf9f4",
        "on-surface":                 "#1c1c19",
        "surface-variant":            "#e5e2dd",
        "on-surface-variant":         "#59413e",
        "surface-container":          "#f0ede8",
        "surface-container-low":      "#f6f3ee",
        "surface-container-high":     "#ebe8e3",
        "surface-container-lowest":   "#ffffff",
        "surface-container-highest":  "#e5e2dd",
        outline:                      "#8c716c",
        "outline-variant":            "#e0bfba",
        "inverse-surface":            "#31302d",
        "inverse-on-surface":         "#f3f0eb",
      },
      fontFamily: {
        serif:    ["Noto Serif", "serif"],
        sans:     ["Manrope", "sans-serif"],
        body:     ["Manrope", "sans-serif"],
        headline: ["Noto Serif", "serif"],
      },
    },
  },
};
